/**
 * This class is generated by jOOQ
 */
package model.dbo;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dbo extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -497707597;

	/**
	 * The singleton instance of <code>dbo</code>
	 */
	public static final Dbo DBO = new Dbo();

	/**
	 * No further instances allowed
	 */
	private Dbo() {
		super("dbo");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			model.dbo.tables.Cena.CENA,
			model.dbo.tables.Dostarcza.DOSTARCZA,
			model.dbo.tables.Dostawca.DOSTAWCA,
			model.dbo.tables.Elementkupiony.ELEMENTKUPIONY,
			model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY,
			model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM,
			model.dbo.tables.Klient.KLIENT,
			model.dbo.tables.Kupno.KUPNO,
			model.dbo.tables.Pracownik.PRACOWNIK,
			model.dbo.tables.Producent.PRODUCENT,
			model.dbo.tables.Reklamacja.REKLAMACJA,
			model.dbo.tables.Rodzajwyrobu.RODZAJWYROBU,
			model.dbo.tables.Skladnik.SKLADNIK,
			model.dbo.tables.Sprzedaz.SPRZEDAZ,
			model.dbo.tables.Wyrob.WYROB);
	}
}
