/**
 * This class is generated by jOOQ
 */
package model.dbo;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>dbo</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<model.dbo.tables.records.CenaRecord, java.lang.Integer> IDENTITY_CENA = Identities0.IDENTITY_CENA;
	public static final org.jooq.Identity<model.dbo.tables.records.DostarczaRecord, java.lang.Integer> IDENTITY_DOSTARCZA = Identities0.IDENTITY_DOSTARCZA;
	public static final org.jooq.Identity<model.dbo.tables.records.DostawcaRecord, java.lang.Integer> IDENTITY_DOSTAWCA = Identities0.IDENTITY_DOSTAWCA;
	public static final org.jooq.Identity<model.dbo.tables.records.ElementkupionyRecord, java.lang.Integer> IDENTITY_ELEMENTKUPIONY = Identities0.IDENTITY_ELEMENTKUPIONY;
	public static final org.jooq.Identity<model.dbo.tables.records.ElementsprzedanyRecord, java.lang.Integer> IDENTITY_ELEMENTSPRZEDANY = Identities0.IDENTITY_ELEMENTSPRZEDANY;
	public static final org.jooq.Identity<model.dbo.tables.records.JestskladnikiemRecord, java.lang.Integer> IDENTITY_JESTSKLADNIKIEM = Identities0.IDENTITY_JESTSKLADNIKIEM;
	public static final org.jooq.Identity<model.dbo.tables.records.KlientRecord, java.lang.Integer> IDENTITY_KLIENT = Identities0.IDENTITY_KLIENT;
	public static final org.jooq.Identity<model.dbo.tables.records.KupnoRecord, java.lang.Integer> IDENTITY_KUPNO = Identities0.IDENTITY_KUPNO;
	public static final org.jooq.Identity<model.dbo.tables.records.ProducentRecord, java.lang.Integer> IDENTITY_PRODUCENT = Identities0.IDENTITY_PRODUCENT;
	public static final org.jooq.Identity<model.dbo.tables.records.ReklamacjaRecord, java.lang.Integer> IDENTITY_REKLAMACJA = Identities0.IDENTITY_REKLAMACJA;
	public static final org.jooq.Identity<model.dbo.tables.records.RodzajwyrobuRecord, java.lang.Integer> IDENTITY_RODZAJWYROBU = Identities0.IDENTITY_RODZAJWYROBU;
	public static final org.jooq.Identity<model.dbo.tables.records.SkladnikRecord, java.lang.Integer> IDENTITY_SKLADNIK = Identities0.IDENTITY_SKLADNIK;
	public static final org.jooq.Identity<model.dbo.tables.records.SprzedazRecord, java.lang.Integer> IDENTITY_SPRZEDAZ = Identities0.IDENTITY_SPRZEDAZ;
	public static final org.jooq.Identity<model.dbo.tables.records.WyrobRecord, java.lang.Integer> IDENTITY_WYROB = Identities0.IDENTITY_WYROB;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<model.dbo.tables.records.CenaRecord> PK__CENA__3213E83F1A71B798 = UniqueKeys0.PK__CENA__3213E83F1A71B798;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.DostarczaRecord> PK__DOSTARCZ__3213E83F92B7C7CF = UniqueKeys0.PK__DOSTARCZ__3213E83F92B7C7CF;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.DostawcaRecord> PK__DOSTAWCA__3213E83F3193CB4F = UniqueKeys0.PK__DOSTAWCA__3213E83F3193CB4F;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.ElementkupionyRecord> PK__ELEMENTK__3213E83F8A4CA118 = UniqueKeys0.PK__ELEMENTK__3213E83F8A4CA118;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.ElementsprzedanyRecord> PK__ELEMENTS__3213E83F72D0AF93 = UniqueKeys0.PK__ELEMENTS__3213E83F72D0AF93;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.JestskladnikiemRecord> PK__JESTSKLA__3213E83F6BD1F6C8 = UniqueKeys0.PK__JESTSKLA__3213E83F6BD1F6C8;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.KlientRecord> PK__KLIENT__3213E83FB9F9825C = UniqueKeys0.PK__KLIENT__3213E83FB9F9825C;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.KupnoRecord> PK__KUPNO__3213E83FDBF8E355 = UniqueKeys0.PK__KUPNO__3213E83FDBF8E355;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.PracownikRecord> PK__PRACOWNI__DC3B1BB9C1C35280 = UniqueKeys0.PK__PRACOWNI__DC3B1BB9C1C35280;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.ProducentRecord> PK__PRODUCEN__3213E83FD580F256 = UniqueKeys0.PK__PRODUCEN__3213E83FD580F256;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.ReklamacjaRecord> PK__REKLAMAC__3213E83F7065CA5F = UniqueKeys0.PK__REKLAMAC__3213E83F7065CA5F;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.RodzajwyrobuRecord> PK__RODZAJWY__3213E83FC0956D24 = UniqueKeys0.PK__RODZAJWY__3213E83FC0956D24;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.SkladnikRecord> PK__SKLADNIK__3213E83F9486E717 = UniqueKeys0.PK__SKLADNIK__3213E83F9486E717;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.SkladnikRecord> UQ__SKLADNIK__F072DFBE25C1174D = UniqueKeys0.UQ__SKLADNIK__F072DFBE25C1174D;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.SprzedazRecord> PK__SPRZEDAZ__3213E83FF4BAECFA = UniqueKeys0.PK__SPRZEDAZ__3213E83FF4BAECFA;
	public static final org.jooq.UniqueKey<model.dbo.tables.records.WyrobRecord> PK__WYROB__3213E83F467AA348 = UniqueKeys0.PK__WYROB__3213E83F467AA348;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<model.dbo.tables.records.CenaRecord, model.dbo.tables.records.WyrobRecord> FK__CENA__IDWYROBU__1273C1CD = ForeignKeys0.FK__CENA__IDWYROBU__1273C1CD;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.DostarczaRecord, model.dbo.tables.records.DostawcaRecord> FK__DOSTARCZA__IDDOS__32E0915F = ForeignKeys0.FK__DOSTARCZA__IDDOS__32E0915F;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.DostarczaRecord, model.dbo.tables.records.WyrobRecord> FK__DOSTARCZA__IDWYR__33D4B598 = ForeignKeys0.FK__DOSTARCZA__IDWYR__33D4B598;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.ElementkupionyRecord, model.dbo.tables.records.KupnoRecord> FK__ELEMENTKU__IDKUP__3C69FB99 = ForeignKeys0.FK__ELEMENTKU__IDKUP__3C69FB99;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.ElementkupionyRecord, model.dbo.tables.records.WyrobRecord> FK__ELEMENTKU__IDWYR__3D5E1FD2 = ForeignKeys0.FK__ELEMENTKU__IDWYR__3D5E1FD2;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.ElementsprzedanyRecord, model.dbo.tables.records.SprzedazRecord> FK__ELEMENTSP__IDSPR__2A4B4B5E = ForeignKeys0.FK__ELEMENTSP__IDSPR__2A4B4B5E;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.ElementsprzedanyRecord, model.dbo.tables.records.WyrobRecord> FK__ELEMENTSP__IDWYR__2B3F6F97 = ForeignKeys0.FK__ELEMENTSP__IDWYR__2B3F6F97;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.JestskladnikiemRecord, model.dbo.tables.records.WyrobRecord> FK__JESTSKLAD__IDWYR__20C1E124 = ForeignKeys0.FK__JESTSKLAD__IDWYR__20C1E124;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.JestskladnikiemRecord, model.dbo.tables.records.SkladnikRecord> FK__JESTSKLAD__IDSKL__21B6055D = ForeignKeys0.FK__JESTSKLAD__IDSKL__21B6055D;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.KupnoRecord, model.dbo.tables.records.DostawcaRecord> FK__KUPNO__IDDOSTAWC__36B12243 = ForeignKeys0.FK__KUPNO__IDDOSTAWC__36B12243;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.KupnoRecord, model.dbo.tables.records.PracownikRecord> FK__KUPNO__IDPRACOWN__37A5467C = ForeignKeys0.FK__KUPNO__IDPRACOWN__37A5467C;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.ReklamacjaRecord, model.dbo.tables.records.SprzedazRecord> FK__REKLAMACJ__IDSPR__403A8C7D = ForeignKeys0.FK__REKLAMACJ__IDSPR__403A8C7D;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.SprzedazRecord, model.dbo.tables.records.KlientRecord> FK__SPRZEDAZ__IDKLIE__24927208 = ForeignKeys0.FK__SPRZEDAZ__IDKLIE__24927208;
	public static final org.jooq.ForeignKey<model.dbo.tables.records.SprzedazRecord, model.dbo.tables.records.PracownikRecord> FK__SPRZEDAZ__IDPRAC__25869641 = ForeignKeys0.FK__SPRZEDAZ__IDPRAC__25869641;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<model.dbo.tables.records.CenaRecord, java.lang.Integer> IDENTITY_CENA = createIdentity(model.dbo.tables.Cena.CENA, model.dbo.tables.Cena.CENA.ID);
		public static org.jooq.Identity<model.dbo.tables.records.DostarczaRecord, java.lang.Integer> IDENTITY_DOSTARCZA = createIdentity(model.dbo.tables.Dostarcza.DOSTARCZA, model.dbo.tables.Dostarcza.DOSTARCZA.ID);
		public static org.jooq.Identity<model.dbo.tables.records.DostawcaRecord, java.lang.Integer> IDENTITY_DOSTAWCA = createIdentity(model.dbo.tables.Dostawca.DOSTAWCA, model.dbo.tables.Dostawca.DOSTAWCA.ID);
		public static org.jooq.Identity<model.dbo.tables.records.ElementkupionyRecord, java.lang.Integer> IDENTITY_ELEMENTKUPIONY = createIdentity(model.dbo.tables.Elementkupiony.ELEMENTKUPIONY, model.dbo.tables.Elementkupiony.ELEMENTKUPIONY.ID);
		public static org.jooq.Identity<model.dbo.tables.records.ElementsprzedanyRecord, java.lang.Integer> IDENTITY_ELEMENTSPRZEDANY = createIdentity(model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY, model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY.ID);
		public static org.jooq.Identity<model.dbo.tables.records.JestskladnikiemRecord, java.lang.Integer> IDENTITY_JESTSKLADNIKIEM = createIdentity(model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM, model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM.ID);
		public static org.jooq.Identity<model.dbo.tables.records.KlientRecord, java.lang.Integer> IDENTITY_KLIENT = createIdentity(model.dbo.tables.Klient.KLIENT, model.dbo.tables.Klient.KLIENT.ID);
		public static org.jooq.Identity<model.dbo.tables.records.KupnoRecord, java.lang.Integer> IDENTITY_KUPNO = createIdentity(model.dbo.tables.Kupno.KUPNO, model.dbo.tables.Kupno.KUPNO.ID);
		public static org.jooq.Identity<model.dbo.tables.records.ProducentRecord, java.lang.Integer> IDENTITY_PRODUCENT = createIdentity(model.dbo.tables.Producent.PRODUCENT, model.dbo.tables.Producent.PRODUCENT.ID);
		public static org.jooq.Identity<model.dbo.tables.records.ReklamacjaRecord, java.lang.Integer> IDENTITY_REKLAMACJA = createIdentity(model.dbo.tables.Reklamacja.REKLAMACJA, model.dbo.tables.Reklamacja.REKLAMACJA.ID);
		public static org.jooq.Identity<model.dbo.tables.records.RodzajwyrobuRecord, java.lang.Integer> IDENTITY_RODZAJWYROBU = createIdentity(model.dbo.tables.Rodzajwyrobu.RODZAJWYROBU, model.dbo.tables.Rodzajwyrobu.RODZAJWYROBU.ID);
		public static org.jooq.Identity<model.dbo.tables.records.SkladnikRecord, java.lang.Integer> IDENTITY_SKLADNIK = createIdentity(model.dbo.tables.Skladnik.SKLADNIK, model.dbo.tables.Skladnik.SKLADNIK.ID);
		public static org.jooq.Identity<model.dbo.tables.records.SprzedazRecord, java.lang.Integer> IDENTITY_SPRZEDAZ = createIdentity(model.dbo.tables.Sprzedaz.SPRZEDAZ, model.dbo.tables.Sprzedaz.SPRZEDAZ.ID);
		public static org.jooq.Identity<model.dbo.tables.records.WyrobRecord, java.lang.Integer> IDENTITY_WYROB = createIdentity(model.dbo.tables.Wyrob.WYROB, model.dbo.tables.Wyrob.WYROB.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<model.dbo.tables.records.CenaRecord> PK__CENA__3213E83F1A71B798 = createUniqueKey(model.dbo.tables.Cena.CENA, model.dbo.tables.Cena.CENA.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.DostarczaRecord> PK__DOSTARCZ__3213E83F92B7C7CF = createUniqueKey(model.dbo.tables.Dostarcza.DOSTARCZA, model.dbo.tables.Dostarcza.DOSTARCZA.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.DostawcaRecord> PK__DOSTAWCA__3213E83F3193CB4F = createUniqueKey(model.dbo.tables.Dostawca.DOSTAWCA, model.dbo.tables.Dostawca.DOSTAWCA.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.ElementkupionyRecord> PK__ELEMENTK__3213E83F8A4CA118 = createUniqueKey(model.dbo.tables.Elementkupiony.ELEMENTKUPIONY, model.dbo.tables.Elementkupiony.ELEMENTKUPIONY.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.ElementsprzedanyRecord> PK__ELEMENTS__3213E83F72D0AF93 = createUniqueKey(model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY, model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.JestskladnikiemRecord> PK__JESTSKLA__3213E83F6BD1F6C8 = createUniqueKey(model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM, model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.KlientRecord> PK__KLIENT__3213E83FB9F9825C = createUniqueKey(model.dbo.tables.Klient.KLIENT, model.dbo.tables.Klient.KLIENT.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.KupnoRecord> PK__KUPNO__3213E83FDBF8E355 = createUniqueKey(model.dbo.tables.Kupno.KUPNO, model.dbo.tables.Kupno.KUPNO.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.PracownikRecord> PK__PRACOWNI__DC3B1BB9C1C35280 = createUniqueKey(model.dbo.tables.Pracownik.PRACOWNIK, model.dbo.tables.Pracownik.PRACOWNIK.PESEL);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.ProducentRecord> PK__PRODUCEN__3213E83FD580F256 = createUniqueKey(model.dbo.tables.Producent.PRODUCENT, model.dbo.tables.Producent.PRODUCENT.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.ReklamacjaRecord> PK__REKLAMAC__3213E83F7065CA5F = createUniqueKey(model.dbo.tables.Reklamacja.REKLAMACJA, model.dbo.tables.Reklamacja.REKLAMACJA.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.RodzajwyrobuRecord> PK__RODZAJWY__3213E83FC0956D24 = createUniqueKey(model.dbo.tables.Rodzajwyrobu.RODZAJWYROBU, model.dbo.tables.Rodzajwyrobu.RODZAJWYROBU.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.SkladnikRecord> PK__SKLADNIK__3213E83F9486E717 = createUniqueKey(model.dbo.tables.Skladnik.SKLADNIK, model.dbo.tables.Skladnik.SKLADNIK.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.SkladnikRecord> UQ__SKLADNIK__F072DFBE25C1174D = createUniqueKey(model.dbo.tables.Skladnik.SKLADNIK, model.dbo.tables.Skladnik.SKLADNIK.NAZWA);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.SprzedazRecord> PK__SPRZEDAZ__3213E83FF4BAECFA = createUniqueKey(model.dbo.tables.Sprzedaz.SPRZEDAZ, model.dbo.tables.Sprzedaz.SPRZEDAZ.ID);
		public static final org.jooq.UniqueKey<model.dbo.tables.records.WyrobRecord> PK__WYROB__3213E83F467AA348 = createUniqueKey(model.dbo.tables.Wyrob.WYROB, model.dbo.tables.Wyrob.WYROB.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<model.dbo.tables.records.CenaRecord, model.dbo.tables.records.WyrobRecord> FK__CENA__IDWYROBU__1273C1CD = createForeignKey(model.dbo.Keys.PK__WYROB__3213E83F467AA348, model.dbo.tables.Cena.CENA, model.dbo.tables.Cena.CENA.IDWYROBU);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.DostarczaRecord, model.dbo.tables.records.DostawcaRecord> FK__DOSTARCZA__IDDOS__32E0915F = createForeignKey(model.dbo.Keys.PK__DOSTAWCA__3213E83F3193CB4F, model.dbo.tables.Dostarcza.DOSTARCZA, model.dbo.tables.Dostarcza.DOSTARCZA.IDDOSTAWCY);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.DostarczaRecord, model.dbo.tables.records.WyrobRecord> FK__DOSTARCZA__IDWYR__33D4B598 = createForeignKey(model.dbo.Keys.PK__WYROB__3213E83F467AA348, model.dbo.tables.Dostarcza.DOSTARCZA, model.dbo.tables.Dostarcza.DOSTARCZA.IDWYROBU);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.ElementkupionyRecord, model.dbo.tables.records.KupnoRecord> FK__ELEMENTKU__IDKUP__3C69FB99 = createForeignKey(model.dbo.Keys.PK__KUPNO__3213E83FDBF8E355, model.dbo.tables.Elementkupiony.ELEMENTKUPIONY, model.dbo.tables.Elementkupiony.ELEMENTKUPIONY.IDKUPNA);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.ElementkupionyRecord, model.dbo.tables.records.WyrobRecord> FK__ELEMENTKU__IDWYR__3D5E1FD2 = createForeignKey(model.dbo.Keys.PK__WYROB__3213E83F467AA348, model.dbo.tables.Elementkupiony.ELEMENTKUPIONY, model.dbo.tables.Elementkupiony.ELEMENTKUPIONY.IDWYROBU);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.ElementsprzedanyRecord, model.dbo.tables.records.SprzedazRecord> FK__ELEMENTSP__IDSPR__2A4B4B5E = createForeignKey(model.dbo.Keys.PK__SPRZEDAZ__3213E83FF4BAECFA, model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY, model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY.IDSPRZEDAZY);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.ElementsprzedanyRecord, model.dbo.tables.records.WyrobRecord> FK__ELEMENTSP__IDWYR__2B3F6F97 = createForeignKey(model.dbo.Keys.PK__WYROB__3213E83F467AA348, model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY, model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY.IDWYROBU);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.JestskladnikiemRecord, model.dbo.tables.records.WyrobRecord> FK__JESTSKLAD__IDWYR__20C1E124 = createForeignKey(model.dbo.Keys.PK__WYROB__3213E83F467AA348, model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM, model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM.IDWYROBU);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.JestskladnikiemRecord, model.dbo.tables.records.SkladnikRecord> FK__JESTSKLAD__IDSKL__21B6055D = createForeignKey(model.dbo.Keys.PK__SKLADNIK__3213E83F9486E717, model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM, model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM.IDSKLADNIKA);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.KupnoRecord, model.dbo.tables.records.DostawcaRecord> FK__KUPNO__IDDOSTAWC__36B12243 = createForeignKey(model.dbo.Keys.PK__DOSTAWCA__3213E83F3193CB4F, model.dbo.tables.Kupno.KUPNO, model.dbo.tables.Kupno.KUPNO.IDDOSTAWCY);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.KupnoRecord, model.dbo.tables.records.PracownikRecord> FK__KUPNO__IDPRACOWN__37A5467C = createForeignKey(model.dbo.Keys.PK__PRACOWNI__DC3B1BB9C1C35280, model.dbo.tables.Kupno.KUPNO, model.dbo.tables.Kupno.KUPNO.IDPRACOWNIKA);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.ReklamacjaRecord, model.dbo.tables.records.SprzedazRecord> FK__REKLAMACJ__IDSPR__403A8C7D = createForeignKey(model.dbo.Keys.PK__SPRZEDAZ__3213E83FF4BAECFA, model.dbo.tables.Reklamacja.REKLAMACJA, model.dbo.tables.Reklamacja.REKLAMACJA.IDSPRZEDAZY);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.SprzedazRecord, model.dbo.tables.records.KlientRecord> FK__SPRZEDAZ__IDKLIE__24927208 = createForeignKey(model.dbo.Keys.PK__KLIENT__3213E83FB9F9825C, model.dbo.tables.Sprzedaz.SPRZEDAZ, model.dbo.tables.Sprzedaz.SPRZEDAZ.IDKLIENTA);
		public static final org.jooq.ForeignKey<model.dbo.tables.records.SprzedazRecord, model.dbo.tables.records.PracownikRecord> FK__SPRZEDAZ__IDPRAC__25869641 = createForeignKey(model.dbo.Keys.PK__PRACOWNI__DC3B1BB9C1C35280, model.dbo.tables.Sprzedaz.SPRZEDAZ, model.dbo.tables.Sprzedaz.SPRZEDAZ.IDPRACOWNIKA);
	}
}
