/**
 * This class is generated by jOOQ
 */
package model.dbo;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in dbo
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table dbo.cena
	 */
	public static final model.dbo.tables.Cena CENA = model.dbo.tables.Cena.CENA;

	/**
	 * The table dbo.dostarcza
	 */
	public static final model.dbo.tables.Dostarcza DOSTARCZA = model.dbo.tables.Dostarcza.DOSTARCZA;

	/**
	 * The table dbo.dostawca
	 */
	public static final model.dbo.tables.Dostawca DOSTAWCA = model.dbo.tables.Dostawca.DOSTAWCA;

	/**
	 * The table dbo.elementKupiony
	 */
	public static final model.dbo.tables.Elementkupiony ELEMENTKUPIONY = model.dbo.tables.Elementkupiony.ELEMENTKUPIONY;

	/**
	 * The table dbo.elementSprzedany
	 */
	public static final model.dbo.tables.Elementsprzedany ELEMENTSPRZEDANY = model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY;

	/**
	 * The table dbo.jestSkladnikiem
	 */
	public static final model.dbo.tables.Jestskladnikiem JESTSKLADNIKIEM = model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM;

	/**
	 * The table dbo.klient
	 */
	public static final model.dbo.tables.Klient KLIENT = model.dbo.tables.Klient.KLIENT;

	/**
	 * The table dbo.kupno
	 */
	public static final model.dbo.tables.Kupno KUPNO = model.dbo.tables.Kupno.KUPNO;

	/**
	 * The table dbo.pracownik
	 */
	public static final model.dbo.tables.Pracownik PRACOWNIK = model.dbo.tables.Pracownik.PRACOWNIK;

	/**
	 * The table dbo.producent
	 */
	public static final model.dbo.tables.Producent PRODUCENT = model.dbo.tables.Producent.PRODUCENT;

	/**
	 * The table dbo.reklamacja
	 */
	public static final model.dbo.tables.Reklamacja REKLAMACJA = model.dbo.tables.Reklamacja.REKLAMACJA;

	/**
	 * The table dbo.rodzajWyrobu
	 */
	public static final model.dbo.tables.Rodzajwyrobu RODZAJWYROBU = model.dbo.tables.Rodzajwyrobu.RODZAJWYROBU;

	/**
	 * The table dbo.skladnik
	 */
	public static final model.dbo.tables.Skladnik SKLADNIK = model.dbo.tables.Skladnik.SKLADNIK;

	/**
	 * The table dbo.sprzedaz
	 */
	public static final model.dbo.tables.Sprzedaz SPRZEDAZ = model.dbo.tables.Sprzedaz.SPRZEDAZ;

	/**
	 * The table dbo.wyrob
	 */
	public static final model.dbo.tables.Wyrob WYROB = model.dbo.tables.Wyrob.WYROB;
}
