/**
 * This class is generated by jOOQ
 */
package model.dbo.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cena extends org.jooq.impl.TableImpl<model.dbo.tables.records.CenaRecord> {

	private static final long serialVersionUID = -883070986;

	/**
	 * The singleton instance of <code>dbo.cena</code>
	 */
	public static final model.dbo.tables.Cena CENA = new model.dbo.tables.Cena();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.dbo.tables.records.CenaRecord> getRecordType() {
		return model.dbo.tables.records.CenaRecord.class;
	}

	/**
	 * The column <code>dbo.cena.id</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.CenaRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.cena.idWyrobu</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.CenaRecord, java.lang.Integer> IDWYROBU = createField("idWyrobu", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.cena.cenaBrutto</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.CenaRecord, java.lang.Double> CENABRUTTO = createField("cenaBrutto", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * The column <code>dbo.cena.dataZmiany</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.CenaRecord, java.sql.Timestamp> DATAZMIANY = createField("dataZmiany", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>dbo.cena</code> table reference
	 */
	public Cena() {
		super("cena", model.dbo.Dbo.DBO);
	}

	/**
	 * Create an aliased <code>dbo.cena</code> table reference
	 */
	public Cena(java.lang.String alias) {
		super(alias, model.dbo.Dbo.DBO, model.dbo.tables.Cena.CENA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.dbo.tables.records.CenaRecord, java.lang.Integer> getIdentity() {
		return model.dbo.Keys.IDENTITY_CENA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.dbo.tables.records.CenaRecord> getPrimaryKey() {
		return model.dbo.Keys.PK__CENA__3213E83F1A71B798;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.dbo.tables.records.CenaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.dbo.tables.records.CenaRecord>>asList(model.dbo.Keys.PK__CENA__3213E83F1A71B798);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<model.dbo.tables.records.CenaRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<model.dbo.tables.records.CenaRecord, ?>>asList(model.dbo.Keys.FK__CENA__IDWYROBU__1273C1CD);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.dbo.tables.Cena as(java.lang.String alias) {
		return new model.dbo.tables.Cena(alias);
	}
}
