/**
 * This class is generated by jOOQ
 */
package model.dbo.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dostawca extends org.jooq.impl.TableImpl<model.dbo.tables.records.DostawcaRecord> {

	private static final long serialVersionUID = 1145163882;

	/**
	 * The singleton instance of <code>dbo.dostawca</code>
	 */
	public static final model.dbo.tables.Dostawca DOSTAWCA = new model.dbo.tables.Dostawca();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.dbo.tables.records.DostawcaRecord> getRecordType() {
		return model.dbo.tables.records.DostawcaRecord.class;
	}

	/**
	 * The column <code>dbo.dostawca.id</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostawcaRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.dostawca.nazwa</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostawcaRecord, java.lang.String> NAZWA = createField("nazwa", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>dbo.dostawca.ulica</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostawcaRecord, java.lang.String> ULICA = createField("ulica", org.jooq.impl.SQLDataType.VARCHAR.length(80), this);

	/**
	 * The column <code>dbo.dostawca.miejscowosc</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostawcaRecord, java.lang.String> MIEJSCOWOSC = createField("miejscowosc", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>dbo.dostawca.kodPocztowy</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostawcaRecord, java.lang.String> KODPOCZTOWY = createField("kodPocztowy", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>dbo.dostawca.telefon</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostawcaRecord, java.lang.String> TELEFON = createField("telefon", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>dbo.dostawca.www</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostawcaRecord, java.lang.String> WWW = createField("www", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>dbo.dostawca.nip</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostawcaRecord, java.lang.String> NIP = createField("nip", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>dbo.dostawca.osobaKontaktowa</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostawcaRecord, java.lang.String> OSOBAKONTAKTOWA = createField("osobaKontaktowa", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * Create a <code>dbo.dostawca</code> table reference
	 */
	public Dostawca() {
		super("dostawca", model.dbo.Dbo.DBO);
	}

	/**
	 * Create an aliased <code>dbo.dostawca</code> table reference
	 */
	public Dostawca(java.lang.String alias) {
		super(alias, model.dbo.Dbo.DBO, model.dbo.tables.Dostawca.DOSTAWCA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.dbo.tables.records.DostawcaRecord, java.lang.Integer> getIdentity() {
		return model.dbo.Keys.IDENTITY_DOSTAWCA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.dbo.tables.records.DostawcaRecord> getPrimaryKey() {
		return model.dbo.Keys.PK__DOSTAWCA__3213E83F3193CB4F;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.dbo.tables.records.DostawcaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.dbo.tables.records.DostawcaRecord>>asList(model.dbo.Keys.PK__DOSTAWCA__3213E83F3193CB4F);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.dbo.tables.Dostawca as(java.lang.String alias) {
		return new model.dbo.tables.Dostawca(alias);
	}
}
