/**
 * This class is generated by jOOQ
 */
package model.dbo.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dostarcza extends org.jooq.impl.TableImpl<model.dbo.tables.records.DostarczaRecord> {

	private static final long serialVersionUID = -526443974;

	/**
	 * The singleton instance of <code>dbo.dostarcza</code>
	 */
	public static final model.dbo.tables.Dostarcza DOSTARCZA = new model.dbo.tables.Dostarcza();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.dbo.tables.records.DostarczaRecord> getRecordType() {
		return model.dbo.tables.records.DostarczaRecord.class;
	}

	/**
	 * The column <code>dbo.dostarcza.id</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostarczaRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.dostarcza.idDostawcy</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostarczaRecord, java.lang.Integer> IDDOSTAWCY = createField("idDostawcy", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.dostarcza.idWyrobu</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.DostarczaRecord, java.lang.Integer> IDWYROBU = createField("idWyrobu", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>dbo.dostarcza</code> table reference
	 */
	public Dostarcza() {
		super("dostarcza", model.dbo.Dbo.DBO);
	}

	/**
	 * Create an aliased <code>dbo.dostarcza</code> table reference
	 */
	public Dostarcza(java.lang.String alias) {
		super(alias, model.dbo.Dbo.DBO, model.dbo.tables.Dostarcza.DOSTARCZA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.dbo.tables.records.DostarczaRecord, java.lang.Integer> getIdentity() {
		return model.dbo.Keys.IDENTITY_DOSTARCZA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.dbo.tables.records.DostarczaRecord> getPrimaryKey() {
		return model.dbo.Keys.PK__DOSTARCZ__3213E83F92B7C7CF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.dbo.tables.records.DostarczaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.dbo.tables.records.DostarczaRecord>>asList(model.dbo.Keys.PK__DOSTARCZ__3213E83F92B7C7CF);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<model.dbo.tables.records.DostarczaRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<model.dbo.tables.records.DostarczaRecord, ?>>asList(model.dbo.Keys.FK__DOSTARCZA__IDDOS__32E0915F, model.dbo.Keys.FK__DOSTARCZA__IDWYR__33D4B598);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.dbo.tables.Dostarcza as(java.lang.String alias) {
		return new model.dbo.tables.Dostarcza(alias);
	}
}
