/**
 * This class is generated by jOOQ
 */
package model.dbo.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Elementsprzedany extends org.jooq.impl.TableImpl<model.dbo.tables.records.ElementsprzedanyRecord> {

	private static final long serialVersionUID = 2116816399;

	/**
	 * The singleton instance of <code>dbo.elementSprzedany</code>
	 */
	public static final model.dbo.tables.Elementsprzedany ELEMENTSPRZEDANY = new model.dbo.tables.Elementsprzedany();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.dbo.tables.records.ElementsprzedanyRecord> getRecordType() {
		return model.dbo.tables.records.ElementsprzedanyRecord.class;
	}

	/**
	 * The column <code>dbo.elementSprzedany.id</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.ElementsprzedanyRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.elementSprzedany.idSprzedazy</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.ElementsprzedanyRecord, java.lang.Integer> IDSPRZEDAZY = createField("idSprzedazy", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.elementSprzedany.idWyrobu</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.ElementsprzedanyRecord, java.lang.Integer> IDWYROBU = createField("idWyrobu", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.elementSprzedany.ilosc</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.ElementsprzedanyRecord, java.lang.Integer> ILOSC = createField("ilosc", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>dbo.elementSprzedany</code> table reference
	 */
	public Elementsprzedany() {
		super("elementSprzedany", model.dbo.Dbo.DBO);
	}

	/**
	 * Create an aliased <code>dbo.elementSprzedany</code> table reference
	 */
	public Elementsprzedany(java.lang.String alias) {
		super(alias, model.dbo.Dbo.DBO, model.dbo.tables.Elementsprzedany.ELEMENTSPRZEDANY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.dbo.tables.records.ElementsprzedanyRecord, java.lang.Integer> getIdentity() {
		return model.dbo.Keys.IDENTITY_ELEMENTSPRZEDANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.dbo.tables.records.ElementsprzedanyRecord> getPrimaryKey() {
		return model.dbo.Keys.PK__ELEMENTS__3213E83FBB53804D;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.dbo.tables.records.ElementsprzedanyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.dbo.tables.records.ElementsprzedanyRecord>>asList(model.dbo.Keys.PK__ELEMENTS__3213E83FBB53804D);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<model.dbo.tables.records.ElementsprzedanyRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<model.dbo.tables.records.ElementsprzedanyRecord, ?>>asList(model.dbo.Keys.FK__ELEMENTSP__IDSPR__2A4B4B5E, model.dbo.Keys.FK__ELEMENTSP__IDWYR__2B3F6F97);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.dbo.tables.Elementsprzedany as(java.lang.String alias) {
		return new model.dbo.tables.Elementsprzedany(alias);
	}
}
