/**
 * This class is generated by jOOQ
 */
package model.dbo.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jestskladnikiem extends org.jooq.impl.TableImpl<model.dbo.tables.records.JestskladnikiemRecord> {

	private static final long serialVersionUID = 216210224;

	/**
	 * The singleton instance of <code>dbo.jestSkladnikiem</code>
	 */
	public static final model.dbo.tables.Jestskladnikiem JESTSKLADNIKIEM = new model.dbo.tables.Jestskladnikiem();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.dbo.tables.records.JestskladnikiemRecord> getRecordType() {
		return model.dbo.tables.records.JestskladnikiemRecord.class;
	}

	/**
	 * The column <code>dbo.jestSkladnikiem.id</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.JestskladnikiemRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.jestSkladnikiem.idWyrobu</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.JestskladnikiemRecord, java.lang.Integer> IDWYROBU = createField("idWyrobu", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.jestSkladnikiem.idSkladnika</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.JestskladnikiemRecord, java.lang.Integer> IDSKLADNIKA = createField("idSkladnika", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.jestSkladnikiem.ilosc</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.JestskladnikiemRecord, java.lang.Integer> ILOSC = createField("ilosc", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.jestSkladnikiem.jednostka</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.JestskladnikiemRecord, java.lang.String> JEDNOSTKA = createField("jednostka", org.jooq.impl.SQLDataType.VARCHAR.length(6), this);

	/**
	 * Create a <code>dbo.jestSkladnikiem</code> table reference
	 */
	public Jestskladnikiem() {
		super("jestSkladnikiem", model.dbo.Dbo.DBO);
	}

	/**
	 * Create an aliased <code>dbo.jestSkladnikiem</code> table reference
	 */
	public Jestskladnikiem(java.lang.String alias) {
		super(alias, model.dbo.Dbo.DBO, model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.dbo.tables.records.JestskladnikiemRecord, java.lang.Integer> getIdentity() {
		return model.dbo.Keys.IDENTITY_JESTSKLADNIKIEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.dbo.tables.records.JestskladnikiemRecord> getPrimaryKey() {
		return model.dbo.Keys.PK__JESTSKLA__3213E83F6BD1F6C8;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.dbo.tables.records.JestskladnikiemRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.dbo.tables.records.JestskladnikiemRecord>>asList(model.dbo.Keys.PK__JESTSKLA__3213E83F6BD1F6C8);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<model.dbo.tables.records.JestskladnikiemRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<model.dbo.tables.records.JestskladnikiemRecord, ?>>asList(model.dbo.Keys.FK__JESTSKLAD__IDWYR__20C1E124, model.dbo.Keys.FK__JESTSKLAD__IDSKL__21B6055D);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.dbo.tables.Jestskladnikiem as(java.lang.String alias) {
		return new model.dbo.tables.Jestskladnikiem(alias);
	}
}
