/**
 * This class is generated by jOOQ
 */
package model.dbo.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Klient extends org.jooq.impl.TableImpl<model.dbo.tables.records.KlientRecord> {

	private static final long serialVersionUID = 1398583642;

	/**
	 * The singleton instance of <code>dbo.klient</code>
	 */
	public static final model.dbo.tables.Klient KLIENT = new model.dbo.tables.Klient();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.dbo.tables.records.KlientRecord> getRecordType() {
		return model.dbo.tables.records.KlientRecord.class;
	}

	/**
	 * The column <code>dbo.klient.id</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.KlientRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.klient.nazwa</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.KlientRecord, java.lang.String> NAZWA = createField("nazwa", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>dbo.klient.ulica</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.KlientRecord, java.lang.String> ULICA = createField("ulica", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>dbo.klient.miejscowosc</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.KlientRecord, java.lang.String> MIEJSCOWOSC = createField("miejscowosc", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>dbo.klient.kodPocztowy</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.KlientRecord, java.lang.String> KODPOCZTOWY = createField("kodPocztowy", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>dbo.klient.telefon</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.KlientRecord, java.lang.String> TELEFON = createField("telefon", org.jooq.impl.SQLDataType.VARCHAR.length(30), this);

	/**
	 * The column <code>dbo.klient.www</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.KlientRecord, java.lang.String> WWW = createField("www", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>dbo.klient.nip</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.KlientRecord, java.lang.String> NIP = createField("nip", org.jooq.impl.SQLDataType.VARCHAR.length(20), this);

	/**
	 * The column <code>dbo.klient.osobaKontaktowa</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.KlientRecord, java.lang.String> OSOBAKONTAKTOWA = createField("osobaKontaktowa", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>dbo.klient</code> table reference
	 */
	public Klient() {
		super("klient", model.dbo.Dbo.DBO);
	}

	/**
	 * Create an aliased <code>dbo.klient</code> table reference
	 */
	public Klient(java.lang.String alias) {
		super(alias, model.dbo.Dbo.DBO, model.dbo.tables.Klient.KLIENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.dbo.tables.records.KlientRecord, java.lang.Integer> getIdentity() {
		return model.dbo.Keys.IDENTITY_KLIENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.dbo.tables.records.KlientRecord> getPrimaryKey() {
		return model.dbo.Keys.PK__KLIENT__3213E83FF1C478B6;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.dbo.tables.records.KlientRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.dbo.tables.records.KlientRecord>>asList(model.dbo.Keys.PK__KLIENT__3213E83FF1C478B6);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.dbo.tables.Klient as(java.lang.String alias) {
		return new model.dbo.tables.Klient(alias);
	}
}
