/**
 * This class is generated by jOOQ
 */
package model.dbo.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rodzajwyrobu extends org.jooq.impl.TableImpl<model.dbo.tables.records.RodzajwyrobuRecord> {

	private static final long serialVersionUID = -1863345538;

	/**
	 * The singleton instance of <code>dbo.rodzajWyrobu</code>
	 */
	public static final model.dbo.tables.Rodzajwyrobu RODZAJWYROBU = new model.dbo.tables.Rodzajwyrobu();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.dbo.tables.records.RodzajwyrobuRecord> getRecordType() {
		return model.dbo.tables.records.RodzajwyrobuRecord.class;
	}

	/**
	 * The column <code>dbo.rodzajWyrobu.id</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.RodzajwyrobuRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.rodzajWyrobu.rodzaj</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.RodzajwyrobuRecord, java.lang.String> RODZAJ = createField("rodzaj", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>dbo.rodzajWyrobu</code> table reference
	 */
	public Rodzajwyrobu() {
		super("rodzajWyrobu", model.dbo.Dbo.DBO);
	}

	/**
	 * Create an aliased <code>dbo.rodzajWyrobu</code> table reference
	 */
	public Rodzajwyrobu(java.lang.String alias) {
		super(alias, model.dbo.Dbo.DBO, model.dbo.tables.Rodzajwyrobu.RODZAJWYROBU);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.dbo.tables.records.RodzajwyrobuRecord, java.lang.Integer> getIdentity() {
		return model.dbo.Keys.IDENTITY_RODZAJWYROBU;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.dbo.tables.records.RodzajwyrobuRecord> getPrimaryKey() {
		return model.dbo.Keys.PK__RODZAJWY__3213E83F0637179D;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.dbo.tables.records.RodzajwyrobuRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.dbo.tables.records.RodzajwyrobuRecord>>asList(model.dbo.Keys.PK__RODZAJWY__3213E83F0637179D);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.dbo.tables.Rodzajwyrobu as(java.lang.String alias) {
		return new model.dbo.tables.Rodzajwyrobu(alias);
	}
}
