/**
 * This class is generated by jOOQ
 */
package model.dbo.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Skladnik extends org.jooq.impl.TableImpl<model.dbo.tables.records.SkladnikRecord> {

	private static final long serialVersionUID = 757842065;

	/**
	 * The singleton instance of <code>dbo.skladnik</code>
	 */
	public static final model.dbo.tables.Skladnik SKLADNIK = new model.dbo.tables.Skladnik();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.dbo.tables.records.SkladnikRecord> getRecordType() {
		return model.dbo.tables.records.SkladnikRecord.class;
	}

	/**
	 * The column <code>dbo.skladnik.id</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.SkladnikRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>dbo.skladnik.nazwa</code>. 
	 */
	public final org.jooq.TableField<model.dbo.tables.records.SkladnikRecord, java.lang.String> NAZWA = createField("nazwa", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>dbo.skladnik</code> table reference
	 */
	public Skladnik() {
		super("skladnik", model.dbo.Dbo.DBO);
	}

	/**
	 * Create an aliased <code>dbo.skladnik</code> table reference
	 */
	public Skladnik(java.lang.String alias) {
		super(alias, model.dbo.Dbo.DBO, model.dbo.tables.Skladnik.SKLADNIK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.dbo.tables.records.SkladnikRecord, java.lang.Integer> getIdentity() {
		return model.dbo.Keys.IDENTITY_SKLADNIK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.dbo.tables.records.SkladnikRecord> getPrimaryKey() {
		return model.dbo.Keys.PK__SKLADNIK__3213E83F07622D28;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.dbo.tables.records.SkladnikRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.dbo.tables.records.SkladnikRecord>>asList(model.dbo.Keys.PK__SKLADNIK__3213E83F07622D28, model.dbo.Keys.UQ__SKLADNIK__F072DFBEC6CFAEFA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.dbo.tables.Skladnik as(java.lang.String alias) {
		return new model.dbo.tables.Skladnik(alias);
	}
}
