/**
 * This class is generated by jOOQ
 */
package model.dbo.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CenakupnaRecord extends org.jooq.impl.UpdatableRecordImpl<model.dbo.tables.records.CenakupnaRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.Double, java.sql.Timestamp> {

	private static final long serialVersionUID = -1433566490;

	/**
	 * Setter for <code>dbo.cenaKupna.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dbo.cenaKupna.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dbo.cenaKupna.idDostarcza</code>. 
	 */
	public void setIddostarcza(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dbo.cenaKupna.idDostarcza</code>. 
	 */
	public java.lang.Integer getIddostarcza() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>dbo.cenaKupna.cenaBrutto</code>. 
	 */
	public void setCenabrutto(java.lang.Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dbo.cenaKupna.cenaBrutto</code>. 
	 */
	public java.lang.Double getCenabrutto() {
		return (java.lang.Double) getValue(2);
	}

	/**
	 * Setter for <code>dbo.cenaKupna.dataZmiany</code>. 
	 */
	public void setDatazmiany(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dbo.cenaKupna.dataZmiany</code>. 
	 */
	public java.sql.Timestamp getDatazmiany() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Double, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Double, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.dbo.tables.Cenakupna.CENAKUPNA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return model.dbo.tables.Cenakupna.CENAKUPNA.IDDOSTARCZA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field3() {
		return model.dbo.tables.Cenakupna.CENAKUPNA.CENABRUTTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return model.dbo.tables.Cenakupna.CENAKUPNA.DATAZMIANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIddostarcza();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value3() {
		return getCenabrutto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getDatazmiany();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CenakupnaRecord
	 */
	public CenakupnaRecord() {
		super(model.dbo.tables.Cenakupna.CENAKUPNA);
	}
}
