/**
 * This class is generated by jOOQ
 */
package model.dbo.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DostarczaRecord extends org.jooq.impl.UpdatableRecordImpl<model.dbo.tables.records.DostarczaRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -86416097;

	/**
	 * Setter for <code>dbo.dostarcza.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dbo.dostarcza.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dbo.dostarcza.idDostawcy</code>. 
	 */
	public void setIddostawcy(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dbo.dostarcza.idDostawcy</code>. 
	 */
	public java.lang.Integer getIddostawcy() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>dbo.dostarcza.idWyrobu</code>. 
	 */
	public void setIdwyrobu(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dbo.dostarcza.idWyrobu</code>. 
	 */
	public java.lang.Integer getIdwyrobu() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.dbo.tables.Dostarcza.DOSTARCZA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return model.dbo.tables.Dostarcza.DOSTARCZA.IDDOSTAWCY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return model.dbo.tables.Dostarcza.DOSTARCZA.IDWYROBU;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIddostawcy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getIdwyrobu();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DostarczaRecord
	 */
	public DostarczaRecord() {
		super(model.dbo.tables.Dostarcza.DOSTARCZA);
	}
}
