/**
 * This class is generated by jOOQ
 */
package model.dbo.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ElementkupionyRecord extends org.jooq.impl.UpdatableRecordImpl<model.dbo.tables.records.ElementkupionyRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1021162664;

	/**
	 * Setter for <code>dbo.elementKupiony.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dbo.elementKupiony.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dbo.elementKupiony.idKupna</code>. 
	 */
	public void setIdkupna(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dbo.elementKupiony.idKupna</code>. 
	 */
	public java.lang.Integer getIdkupna() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>dbo.elementKupiony.idWyrobu</code>. 
	 */
	public void setIdwyrobu(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dbo.elementKupiony.idWyrobu</code>. 
	 */
	public java.lang.Integer getIdwyrobu() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>dbo.elementKupiony.ilosc</code>. 
	 */
	public void setIlosc(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dbo.elementKupiony.ilosc</code>. 
	 */
	public java.lang.Integer getIlosc() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.dbo.tables.Elementkupiony.ELEMENTKUPIONY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return model.dbo.tables.Elementkupiony.ELEMENTKUPIONY.IDKUPNA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return model.dbo.tables.Elementkupiony.ELEMENTKUPIONY.IDWYROBU;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return model.dbo.tables.Elementkupiony.ELEMENTKUPIONY.ILOSC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdkupna();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getIdwyrobu();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getIlosc();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ElementkupionyRecord
	 */
	public ElementkupionyRecord() {
		super(model.dbo.tables.Elementkupiony.ELEMENTKUPIONY);
	}
}
