/**
 * This class is generated by jOOQ
 */
package model.dbo.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JestskladnikiemRecord extends org.jooq.impl.UpdatableRecordImpl<model.dbo.tables.records.JestskladnikiemRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -695677051;

	/**
	 * Setter for <code>dbo.jestSkladnikiem.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dbo.jestSkladnikiem.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dbo.jestSkladnikiem.idWyrobu</code>. 
	 */
	public void setIdwyrobu(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dbo.jestSkladnikiem.idWyrobu</code>. 
	 */
	public java.lang.Integer getIdwyrobu() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>dbo.jestSkladnikiem.idSkladnika</code>. 
	 */
	public void setIdskladnika(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dbo.jestSkladnikiem.idSkladnika</code>. 
	 */
	public java.lang.Integer getIdskladnika() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>dbo.jestSkladnikiem.ilosc</code>. 
	 */
	public void setIlosc(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dbo.jestSkladnikiem.ilosc</code>. 
	 */
	public java.lang.Integer getIlosc() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>dbo.jestSkladnikiem.jednostka</code>. 
	 */
	public void setJednostka(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dbo.jestSkladnikiem.jednostka</code>. 
	 */
	public java.lang.String getJednostka() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM.IDWYROBU;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM.IDSKLADNIKA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM.ILOSC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM.JEDNOSTKA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdwyrobu();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getIdskladnika();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getIlosc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getJednostka();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JestskladnikiemRecord
	 */
	public JestskladnikiemRecord() {
		super(model.dbo.tables.Jestskladnikiem.JESTSKLADNIKIEM);
	}
}
