/**
 * This class is generated by jOOQ
 */
package model.dbo.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KupnoRecord extends org.jooq.impl.UpdatableRecordImpl<model.dbo.tables.records.KupnoRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = 454313252;

	/**
	 * Setter for <code>dbo.kupno.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dbo.kupno.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dbo.kupno.idDostawcy</code>. 
	 */
	public void setIddostawcy(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dbo.kupno.idDostawcy</code>. 
	 */
	public java.lang.Integer getIddostawcy() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>dbo.kupno.idPracownika</code>. 
	 */
	public void setIdpracownika(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dbo.kupno.idPracownika</code>. 
	 */
	public java.lang.String getIdpracownika() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>dbo.kupno.dataWprowadzenia</code>. 
	 */
	public void setDatawprowadzenia(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dbo.kupno.dataWprowadzenia</code>. 
	 */
	public java.sql.Timestamp getDatawprowadzenia() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>dbo.kupno.dataZakonczenia</code>. 
	 */
	public void setDatazakonczenia(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dbo.kupno.dataZakonczenia</code>. 
	 */
	public java.sql.Timestamp getDatazakonczenia() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>dbo.kupno.status</code>. 
	 */
	public void setStatus(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dbo.kupno.status</code>. 
	 */
	public java.lang.Integer getStatus() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.dbo.tables.Kupno.KUPNO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return model.dbo.tables.Kupno.KUPNO.IDDOSTAWCY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return model.dbo.tables.Kupno.KUPNO.IDPRACOWNIKA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return model.dbo.tables.Kupno.KUPNO.DATAWPROWADZENIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return model.dbo.tables.Kupno.KUPNO.DATAZAKONCZENIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return model.dbo.tables.Kupno.KUPNO.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIddostawcy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getIdpracownika();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getDatawprowadzenia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getDatazakonczenia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getStatus();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached KupnoRecord
	 */
	public KupnoRecord() {
		super(model.dbo.tables.Kupno.KUPNO);
	}
}
