/**
 * This class is generated by jOOQ
 */
package model.dbo.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReklamacjaRecord extends org.jooq.impl.UpdatableRecordImpl<model.dbo.tables.records.ReklamacjaRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = -1536476758;

	/**
	 * Setter for <code>dbo.reklamacja.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dbo.reklamacja.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dbo.reklamacja.idSprzedazy</code>. 
	 */
	public void setIdsprzedazy(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dbo.reklamacja.idSprzedazy</code>. 
	 */
	public java.lang.Integer getIdsprzedazy() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>dbo.reklamacja.opis</code>. 
	 */
	public void setOpis(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dbo.reklamacja.opis</code>. 
	 */
	public java.lang.String getOpis() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>dbo.reklamacja.zgloszono</code>. 
	 */
	public void setZgloszono(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dbo.reklamacja.zgloszono</code>. 
	 */
	public java.sql.Timestamp getZgloszono() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>dbo.reklamacja.rozpatrzono</code>. 
	 */
	public void setRozpatrzono(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dbo.reklamacja.rozpatrzono</code>. 
	 */
	public java.sql.Timestamp getRozpatrzono() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>dbo.reklamacja.status</code>. 
	 */
	public void setStatus(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dbo.reklamacja.status</code>. 
	 */
	public java.lang.Integer getStatus() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.dbo.tables.Reklamacja.REKLAMACJA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return model.dbo.tables.Reklamacja.REKLAMACJA.IDSPRZEDAZY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return model.dbo.tables.Reklamacja.REKLAMACJA.OPIS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return model.dbo.tables.Reklamacja.REKLAMACJA.ZGLOSZONO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return model.dbo.tables.Reklamacja.REKLAMACJA.ROZPATRZONO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return model.dbo.tables.Reklamacja.REKLAMACJA.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdsprzedazy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getOpis();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getZgloszono();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getRozpatrzono();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getStatus();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReklamacjaRecord
	 */
	public ReklamacjaRecord() {
		super(model.dbo.tables.Reklamacja.REKLAMACJA);
	}
}
