/**
 * This class is generated by jOOQ
 */
package model.dbo.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WyrobRecord extends org.jooq.impl.UpdatableRecordImpl<model.dbo.tables.records.WyrobRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1010372543;

	/**
	 * Setter for <code>dbo.wyrob.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dbo.wyrob.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>dbo.wyrob.nazwa</code>. 
	 */
	public void setNazwa(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dbo.wyrob.nazwa</code>. 
	 */
	public java.lang.String getNazwa() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>dbo.wyrob.iloscDostepnych</code>. 
	 */
	public void setIloscdostepnych(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dbo.wyrob.iloscDostepnych</code>. 
	 */
	public java.lang.Integer getIloscdostepnych() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>dbo.wyrob.producentId</code>. 
	 */
	public void setProducentid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dbo.wyrob.producentId</code>. 
	 */
	public java.lang.Integer getProducentid() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>dbo.wyrob.rodzajWyrobuId</code>. 
	 */
	public void setRodzajwyrobuid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dbo.wyrob.rodzajWyrobuId</code>. 
	 */
	public java.lang.Integer getRodzajwyrobuid() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.dbo.tables.Wyrob.WYROB.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return model.dbo.tables.Wyrob.WYROB.NAZWA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return model.dbo.tables.Wyrob.WYROB.ILOSCDOSTEPNYCH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return model.dbo.tables.Wyrob.WYROB.PRODUCENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return model.dbo.tables.Wyrob.WYROB.RODZAJWYROBUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNazwa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getIloscdostepnych();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getProducentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getRodzajwyrobuid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WyrobRecord
	 */
	public WyrobRecord() {
		super(model.dbo.tables.Wyrob.WYROB);
	}
}
